const ALREADY_EXIST = 422;
const INVALID_ACCESS_TOKEN_STATUS = 401;
const INVALID_CREDENTIAL = 403;
const SUCCESS_STATUS = 200;
const CREATE = 201;
const NO_DATA_FOUND = 200;
const PARAMETER_MISSING_STATUS = 400;
const SHOW_ERROR_MESSAGE = 400;
const ERROR_IN_EXECUTION = 404;
const BAD_REQUEST_STATUS = 500;

module.exports = {
    ALREADY_EXIST,
    INVALID_ACCESS_TOKEN_STATUS,
    INVALID_CREDENTIAL,
    SUCCESS_STATUS,
    CREATE,
    NO_DATA_FOUND,
    PARAMETER_MISSING_STATUS,
    SHOW_ERROR_MESSAGE,
    ERROR_IN_EXECUTION,
    BAD_REQUEST_STATUS
};